# Generated by Django 3.1.1 on 2020-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery', '0003_auto_20201106_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_bill',
            field=models.FloatField(default=10),
        ),
    ]
